### ISSUE TITLE
Actualizacion de la documentación

### ISSUE THREAD

**Issue by AnaOstio** [Arquisoft/dede_es2c#120]
Actualizar la documentacion hasta el punto donde se llegue, falta añadir nuevas dependecias. Hay que revisarla entera y ver que se mantiene y que no.

**Comment by AnaOstio** [comment]
El nombre de la documentacion ha sido arreglado correctamente

**Comment by AnaOstio** [comment]
Habría que realizar los diferentes prototipos de pantalla, actualizando los existentes

**Comment by AnaOstio** [comment]
Se ha actualizado el nombre del grupo

**Comment by AnaOstio** [comment]
Creo que en el punto 1 de la documentación se puede poner aquellas cosas que se pueden realizar en nuestra página

**Comment by UO277189** [comment]
Actualizado el punto 1 indicando que los administradores pueden añadir/eliminar/modificar productos

**Comment by AnaOstio** [comment]
Se ha añadido tanto los prototipos de Admin y se ha buscado un manera de que todos los Prototipos tengan el mismo aspecto, se puede utilizar [Pencil](https://pencil.evolus.vn/)

**Comment by AnaOstio** [comment]
Creo que tambien podriamos añadir en el punto 2 todas las decisiones que estamos tomando (utilizacioón de MUI, Acios, etc...)

**Comment by uo278290** [comment]
Se ha actualizado el punto 5 y el punto 11 de la documentación para el 3er entregable

**Comment by AnaOstio** [comment]
Documentación actualizada
