### ISSUE TITLE
Validación del administrador

### ISSUE THREAD

**Issue by UO277189** [Arquisoft/dede_es2c#156]
Hay que verificar en el backend que el usuario que añade/elimina/modifica productos sea un administrador.

**Comment by uo278290** [comment]
Las rutas está protegidas, un usuario estándar no puede acceder a dichas funcionalidades. Faltaría comprobar en el backend el rol del usuario en las distintas peticiones

**Comment by UO277189** [comment]
Como se comentó arriba, las rutas están protegidas. El backend de roles al final lo gestionó @uo278290
