### ISSUE TITLE
Conexión con los PODs de SOLID en el backend

### ISSUE THREAD

**Issue by uo278290** [Arquisoft/dede_es2c#157]
Está realizada la conexión con los PODs en el backend de la aplicación mediante el nombre del usuario, faltaría ver como conectarlo con el frontend de la aplicación

**Comment by AnaOstio** [comment]
Creo que estaría bien que cuando se vea el sumario de producto con el precio de los productos calculados (IVA * basePrecioProducto) para que ahi podamos comprobar si los campos estan bien obtenidos, ademas de enseñarle al cliente su dirección por si queire cambiar el pod. 

Todo esto que comento se podria realizar mediante un TextField donde el usuario mete su webId, luego se comprueba mediante el pulso en un boton y en funcion del estado que devuelva el backend de la aplicación sacar un modal de Swal enseñando el comentario oportuno

**Comment by AnaOstio** [comment]
Conexion del pod en backend realizado y ademas en front-end tambien se ha asignado un boton para comprobar direcciones
