### ISSUE TITLE
comprobar que el usuario tiene privilegios para entrar a x ruta

### ISSUE THREAD

**Issue by AnaOstio** [Arquisoft/dede_es2c#207]
Se teine que hacer una comprobacion en front para ver que si se accede por url, es correcto el tipo de usuario, ya que ahora mismo se puede acceder por url a cualquier direccion aunque no se tenga premisos para ello

**Comment by AnaOstio** [comment]
Habria que meter algo de links y una imagen como que el acceso esta prohibido

**Comment by uo278290** [comment]
Comprobación hecha para todas las rutas de admin, ahora mismo se redirecciona al login si el usuario no tiene privilegios pero estaría bien que se le mostrase también un aviso.

**Comment by AnaOstio** [comment]
Hecho
