### ISSUE TITLE
Pegatinas del archivo Readme principal

### ISSUE THREAD

**Issue by HugoLebredo** [Arquisoft/dede_es2c#211]
Las pegatinas del archivo Readme no apuntan a vuestro repositorio.

Cambiadlo para la presentación por favor

<img width="532" alt="image" src="https://user-images.githubusercontent.com/58787059/164449596-0c599235-f5cb-4522-9846-557db9135527.png">

**Comment by AnaOstio** [comment]
Están cambiadas, pero ahora mismo el cambio se encuentra en Developer, ya que todavía no hemos terminado de juntar todas las partes @HugoLebredo
