### ISSUE TITLE
Guardar el carrito en base de datos para mantener la sesión

### ISSUE THREAD

**Issue by uo278290** [Arquisoft/dede_es2c#215]
Se guardará y manejará el carrito del cliente en la base de datos de la aplicación para mantenerlo aunque se cierre la sesión o se cambie de navegador.

**Comment by uo278290** [comment]
Ahora mismo está hecho el backend de la funcionalidad, falta conectarlo con el frontend

**Comment by AnaOstio** [comment]
No se realizara de esta manera, hay que hacerlo mediante localStorage
