### ISSUE TITLE
Realizar Pedidos

### ISSUE THREAD

**Issue by AnaOstio** [Arquisoft/dede_es2c#221]
Se necesita que una vez el cliente este satisfecho con los productos seleccionados, este pueda realizar el pago y confimar el pedido

**Comment by AnaOstio** [comment]
Se ha realziado una ventana intermedia de ver el resumen de compra

**Comment by AnaOstio** [comment]
Fallo en la API de envíos, que no sabemos a que se debe todavia. El resto esta completado

**Comment by UO277189** [comment]
El error parece ser relacionado con la falta de uso de try/catch para el manejo de funciones asíncronas. Puse un try/catch en la función encargada de los costes de la API a ver si funciona mejor.

**Comment by AnaOstio** [comment]
Tiene que ver algo con el tema status de la función, estoy mirando a ver si se puede solucionar

**Comment by AnaOstio** [comment]
Solucionado, sobraba una linea en la API, el error fue encontrado por @uo278290, comprobo si al eliminar esa linea petaban los test y no petaban
