### ISSUE TITLE
Actualizacion de Readme

### ISSUE THREAD

**Issue by UO276255** [Arquisoft/dede_es2c#3]
El Readme que se debe actualizar debe de ser el _es, el normal o ambos? @HugoLebredo

**Comment by HugoLebredo** [comment]
Sorry acabo de ver esto 🙏
Solo teneis que utilizar uno. Podeis renombralos para que el de español sea el readme.md. 

Por cierto mirad las URLs del final del readme. Hay un error, no apuntan a vuestro repo 😅 Problemas de utilizar la plantilla, se me escapó

**Comment by AnaOstio** [comment]
Cambios en el readme.md realizados en mi rama, cuando se junte, este cambio debería ser efectivo
