### ISSUE TITLE
Reparto del trabajo Back-End

### ISSUE THREAD

**Issue by AnaOstio** [Arquisoft/dede_es2c#68]
@uo278290: 
   - Enlace de la base de datos
   - Crud de usuarios

@UO277189:
   - Carrito de compra

@AnaOstio 
   - Crud Productos

**Comment by AnaOstio** [comment]
A cerca de los productos ya se ha realizado el findAll de estos

**Comment by UO277189** [comment]
En vez de carro de la compra trabajo con el pedido.
