### ISSUE TITLE
Fallo filtro por precio + id

### ISSUE THREAD

**Issue by AnaOstio** [Arquisoft/dede_es2c#72]
Hay fallo en el precio por Id + precio de los prodcutos. Habria que revisar codigo

**Comment by AnaOstio** [comment]
El filtro por id creo que es un poco arriesgado ya que se haria por el id que genera mongodb para almacenarlo, por lo que en este caso con el filtro por codigo servira. Habria que hacer comprobaciones de que estos no existen y demas.

**Comment by UO277189** [comment]
La ruta de los métodos GET estaba sin completar.

**Comment by AnaOstio** [comment]
Falta filtro por precio

**Comment by AnaOstio** [comment]
Se ha realizado el filtrado por precio y ademas se ha incoporado a la parte webapp
