### ISSUE TITLE
Creacion de issue para revision

### ISSUE THREAD

**Issue by AnaOstio** [Arquisoft/dede_es2c#79]
Cada uno de los integrantes del equipo de desarollo, debera de crear un nuevo issue con su trabajo realizado durante estas 3 semanas y el resto de miembros del equipo de desarollo debera de estar de acuerdo con ese issue

- [x] @AnaOstio 
- [ ] @UO276255 
- [x] @uo278290 
- [x] @UO277189 
- [x] @AdrianSantamarina

**Comment by AnaOstio** [comment]
[Issue](https://github.com/Arquisoft/dede_es2c/issues/102) correspondiente a mi trabajo realizado

**Comment by UO277189** [comment]
Issue correspondiente a mi trabajo realizado: #106
