### ISSUE TITLE
Asignacion de documentacion Ana 

### ISSUE THREAD

**Issue by UO276255** [Arquisoft/dede_es2c#8]
Ana Ostio realizará los puntos 3 y 9 de la documentación
[System Scope and Context] y [Design Decisions]

- [x] Ana Ostio

**Comment by AnaOstio** [comment]
- [ ]  Punto 3: System Scope and Context
- [ ]  Punto 9: Design Decicisions
- [ ]  Punto 6: Diagramas secuencia que corresponda
- [ ] Punto 12: Glosario

**Comment by AnaOstio** [comment]
Acabado partes de documentación

**Comment by AnaOstio** [comment]
El reparto del punto 6 se ha realizado en el siguiente [enlace](https://github.com/Arquisoft/dede_es2c/issues/19)

**Comment by AnaOstio** [comment]
El punto 4 de la documentación fue realizado por Efrén García y Ana Fernández. El punto 4 estaba asignado a este [enlace](https://github.com/Arquisoft/dede_es2c/issues/10)

**Comment by AnaOstio** [comment]
Realización del punto 10 en su totalidad realizado por Ana Fernandez Ostio, correspondiente a este [enlace](https://github.com/Arquisoft/dede_es2c/issues/11)
