### ISSUE TITLE
Contenedores Docker

### ISSUE THREAD

**Issue by AnaOstio** [Arquisoft/dede_es2c#82]
Juntar todo en docker, para que sea mas facil realizar un uso de la aplicación. Ademas hay que buscar el video que ha sido recomendado por le Profesor De Prácticas

**Comment by AdrianSantamarina** [comment]
El video que recomendó Hugo es este https://www.youtube.com/watch?v=CV_Uf3Dq-EU

**Comment by uo278290** [comment]
Se ha conseguido juntar toda la aplicación en un contenedor de docker, pero utilizando el comando npm start de la web app, con el comando npm prod surge un fallo
